### PR TITLE
LT: auth_proxy: Add failed login message

### PR DESCRIPTION
**Pull request by ddunlop**
Looks like it's not to bad to add an error message.

@oiyana Did you have thoughts on what to add here?

We may also want to update the version of solid used...

image

@buzzfeed/content-insights 
@buzzfeed/platform-infra

### CODE REVIEW

**Comment by oiyana** [comment]
Yes and Yes!  
Can we use [form error] (http://solid.buzzfeed.com/forms.html#form-errors)component instead of the message bar? Here is the mock + copy:
screen shot 2017-01-09 at 9 09 49 am

**Comment by ddunlop** [comment]
updated! now with a newer solid as well!
jan-11-2017 18-20-44

**Comment by yellottyellott** [comment]
😍  😍  😍  😍  😍

**Comment by oiyana** [comment]
LGTM! ❤️

**Pull request merged**
